# -*- coding: utf-8 -*-
"""Te damos la bienvenida a Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import streamlit as st
import pandas as pd
from datetime import datetime

# ---------------------------------------------
# CONFIGURACIÓN GENERAL
# ---------------------------------------------
RUTA_EXCEL = "cmms_simulacion_frigorifico.xlsx"

st.set_page_config(
    page_title="CMMS Flota Frigorífica",
    page_icon="❄️",
    layout="wide"
)

# ---------------------------------------------
# FUNCIONES DE BASE DE DATOS (EXCEL)
# ---------------------------------------------
def leer(hoja):
    return pd.read_excel(RUTA_EXCEL, sheet_name=hoja)

def escribir(hoja, df):
    with pd.ExcelWriter(
        RUTA_EXCEL,
        engine="openpyxl",
        mode="a",
        if_sheet_exists="replace"
    ) as writer:
        df.to_excel(writer, sheet_name=hoja, index=False)

# ---------------------------------------------
# INTERFAZ PRINCIPAL
# ---------------------------------------------
st.title("🚚❄️ CMMS – Gestión de Flota Frigorífica")

menu = st.sidebar.radio(
    "Menú Principal",
    [
        "Dashboard",
        "Vehículos",
        "Equipos de Frío",
        "Órdenes de Trabajo",
        "Repuestos"
    ]
)

# ---------------------------------------------
# DASHBOARD
# ---------------------------------------------
if menu == "Dashboard":
    veh = leer("Vehiculos")
    ot = leer("OrdenesTrabajo")

    col1, col2, col3 = st.columns(3)
    col1.metric("🚛 Vehículos", len(veh))
    col2.metric("🛠 Órdenes", len(ot))
    col3.metric(
        "🔧 % Preventivo",
        round((len(ot[ot["tipo"] == "Preventivo"]) / len(ot)) * 100, 2)
        if len(ot) > 0 else 0
    )

    st.subheader("Órdenes por tipo")
    st.bar_chart(ot["tipo"].value_counts())

# ---------------------------------------------
# VEHÍCULOS
# ---------------------------------------------
elif menu == "Vehículos":
    st.subheader("🚛 Flota de Vehículos")
    st.dataframe(leer("Vehiculos"), use_container_width=True)

# ---------------------------------------------
# EQUIPOS DE FRÍO
# ---------------------------------------------
elif menu == "Equipos de Frío":
    st.subheader("❄️ Equipos Thermo King")
    st.dataframe(leer("EquiposFrio"), use_container_width=True)

# ---------------------------------------------
# ÓRDENES DE TRABAJO
# ---------------------------------------------
elif menu == "Órdenes de Trabajo":
    st.subheader("🛠 Órdenes de Trabajo")
    st.dataframe(leer("OrdenesTrabajo"), use_container_width=True)

    st.markdown("### ➕ Crear nueva orden")
    col1, col2, col3 = st.columns(3)

    with col1:
        vehiculo = st.number_input("ID Vehículo", 1, 50)
    with col2:
        tipo = st.selectbox("Tipo", ["Preventivo", "Correctivo"])
    with col3:
        tecnico = st.number_input("ID Técnico", 1, 4)

    if st.button("Crear Orden"):
        ot = leer("OrdenesTrabajo")
        nueva = {
            "idOT": len(ot) + 1,
            "idVehiculo": vehiculo,
            "idEquipo": vehiculo,
            "tipo": tipo,
            "fechaInicio": datetime.now().strftime("%Y-%m-%d"),
            "fechaFin": "",
            "estado": "Abierta",
            "idTecnico": tecnico
        }
        ot = pd.concat([ot, pd.DataFrame([nueva])], ignore_index=True)
        escribir("OrdenesTrabajo", ot)
        st.success("✅ Orden creada correctamente")

# ---------------------------------------------
# REPUESTOS
# ---------------------------------------------
elif menu == "Repuestos":
    st.subheader("📦 Inventario de Repuestos")
    rep = leer("Repuestos")
    st.dataframe(rep, use_container_width=True)

    alerta = rep[rep["stock"] <= rep["stockMinimo"]]
    if not alerta.empty:
        st.error("🚨 Repuestos en stock crítico")
        st.dataframe(alerta, use_container_width=True)
    else:
        st.success("✔ Stock adecuado")